export const correct=[1,3,0,2,1,2];
export const sectionIds=['victory','peace','cooperation','rights','independence','new-order'];
export const questions={vi:[
{prompt:'Ý nghĩa trực tiếp quan trọng nhất của chiến thắng Đồng minh năm 1945 là gì?',options:['Xóa bỏ ngay mọi hình thức áp bức trên thế giới.','Đánh bại các thế lực phát xít, quân phiệt của phe Trục và kết thúc cuộc chiến.','Bảo đảm không còn cuộc chiến tranh nào xảy ra.','Làm mọi nước trở thành đồng minh lâu dài.']},
{prompt:'Nhìn từ tổn thất của dân thường, bài học nào phù hợp nhất khi đánh giá Thế chiến II?',options:['Chỉ cần ghi nhớ các chiến thắng quân sự.','Thiệt hại của chiến tranh chấm dứt ngay khi đầu hàng.','Chiến tranh chỉ tác động đến người lính ngoài mặt trận.','Trân trọng hòa bình, tưởng nhớ nạn nhân và ngăn ngừa thảm họa tương tự.']},
{prompt:'Liên hợp quốc ra đời năm 1945 thể hiện nỗ lực chủ yếu nào của cộng đồng quốc tế?',options:['Xây dựng cơ chế hợp tác để gìn giữ hòa bình và an ninh quốc tế.','Thành lập một chính phủ duy nhất thay thế mọi quốc gia.','Chấm dứt tự động mọi bất đồng giữa các nước.','Chỉ tập trung giải quyết công việc của các nước thắng trận.']},
{prompt:'Các phiên tòa Nürnberg và Tuyên ngôn Quốc tế Nhân quyền năm 1948 thể hiện chuyển biến nào?',options:['Quyền con người chỉ thuộc về công dân các nước thắng trận.','Mọi thủ phạm đã bị xét xử và mọi quyền đã được bảo đảm.','Nỗ lực tăng cường trách nhiệm đối với tội ác và bảo vệ phẩm giá con người.','Luật pháp quốc tế không còn cần thiết sau chiến tranh.']},
{prompt:'Nhận định nào đúng nhất về quan hệ giữa Thế chiến II và phong trào giải phóng dân tộc?',options:['Các thuộc địa đều được trao độc lập ngay trong năm 1945.','Chiến tranh làm suy yếu đế quốc thực dân, tạo điều kiện cho đấu tranh giành độc lập.','Độc lập hoàn toàn do các cường quốc bên ngoài quyết định.','Phong trào độc lập không chịu tác động nào từ chiến tranh.']},
{prompt:'Vì sao không thể đồng nhất kết thúc Thế chiến II với hòa bình bền vững trên toàn thế giới?',options:['Vì Liên hợp quốc chưa từng được thành lập.','Vì phe Trục vẫn giữ nguyên sức mạnh quân sự sau năm 1945.','Vì thế giới tiếp tục đối mặt với Chiến tranh lạnh, xung đột và các cuộc đấu tranh kéo dài.','Vì các nước không cần tái thiết sau chiến tranh.']}
],en:[
{prompt:'What was the most important direct significance of Allied victory in 1945?',options:['It immediately abolished every form of oppression worldwide.','It defeated the fascist and militarist Axis powers and ended the war.','It guaranteed that no future war would occur.','It made every country a permanent ally.']},
{prompt:'Which lesson best reflects the civilian cost of World War II?',options:['Only military victories need to be remembered.','The consequences of war ended immediately with surrender.','War affected only soldiers on the battlefield.','Value peace, remember victims and prevent similar catastrophes.']},
{prompt:'What central international effort did the founding of the United Nations in 1945 represent?',options:['Building cooperation to protect international peace and security.','Creating one government to replace all sovereign states.','Automatically ending every disagreement between countries.','Dealing only with the interests of the victorious countries.']},
{prompt:'What development do the Nuremberg trials and the 1948 Universal Declaration of Human Rights illustrate?',options:['Human rights belonged only to citizens of victorious countries.','Every perpetrator had been tried and every right was already protected.','Efforts to strengthen accountability for atrocities and protect human dignity.','International law was no longer necessary after the war.']},
{prompt:'Which statement best explains the connection between WWII and national liberation movements?',options:['Every colony was granted independence immediately in 1945.','The war weakened colonial empires, creating opportunities for independence struggles.','Independence was determined entirely by outside powers.','Independence movements were unaffected by the war.']},
{prompt:'Why did the end of WWII not mean lasting peace everywhere?',options:['Because the United Nations was never established.','Because the Axis retained its full military power after 1945.','Because the world still faced the Cold War, conflicts and prolonged struggles.','Because no countries needed reconstruction after the war.']}
]};
export const ui={vi:{title:'Trắc nghiệm — Ý nghĩa Thế chiến II',skip:'Đến câu hỏi',mode:'Chế độ quiz',crossword:'Ô chữ',meaning:'Trắc nghiệm ý nghĩa',language:'Ngôn ngữ',heading:'Bạn hiểu ý nghĩa của Thế chiến II đến đâu?',intro:'6 câu hỏi · Mỗi câu 4 lựa chọn · Chọn một đáp án đúng.',question:'Câu hỏi',progress:'Tiến độ',score:'Số câu đúng',answered:'Đã trả lời',choose:'Chọn một đáp án',check:'Kiểm tra đáp án',checked:'Đã kiểm tra',next:'Câu tiếp theo',previous:'Câu trước',results:'Xem kết quả',correct:'Chính xác!',incorrect:'Chưa chính xác.',correctAnswer:'Đáp án đúng',yourAnswer:'Bạn đã chọn',explanation:'Vì sao?',source:'Đối chiếu nguồn',empty:'Chọn một đáp án trước khi kiểm tra.',review:'Xem lại câu trả lời',reset:'Làm lại',resetTitle:'Bắt đầu lượt mới?',resetText:'Điểm số và câu trả lời của phần trắc nghiệm sẽ được xóa. Ô chữ vẫn giữ nguyên tiến độ.',cancel:'Tiếp tục làm',confirm:'Làm lại từ đầu',close:'Đóng',resultTitle:'Hoàn thành phần ý nghĩa!',resultNote:'Điểm tính theo lần kiểm tra đầu tiên của mỗi câu. Chọn một câu dưới đây để xem lại giải thích.',shortcut:'Phím 1–4 để chọn · Enter để kiểm tra',saved:'Tiến độ được giữ trong thẻ trình duyệt này khi đổi chế độ hoặc ngôn ngữ.',unanswered:'Chưa trả lời',navigation:'Chọn câu hỏi',summary:'Kết quả của bạn',nojs:'Bật JavaScript để làm trắc nghiệm.',footer:'Hiểu sự kiện. Nắm ý nghĩa.',resetNotice:'Đã bắt đầu lượt mới.'},en:{title:'Quiz — The significance of WWII',skip:'Skip to question',mode:'Quiz mode',crossword:'Crossword',meaning:'Significance quiz',language:'Language',heading:'How well do you understand WWII’s significance?',intro:'6 questions · 4 options each · Choose one correct answer.',question:'Question',progress:'Progress',score:'Correct answers',answered:'Answered',choose:'Choose one answer',check:'Check answer',checked:'Checked',next:'Next question',previous:'Previous',results:'View results',correct:'Correct!',incorrect:'Not quite.',correctAnswer:'Correct answer',yourAnswer:'Your answer',explanation:'Why?',source:'Check the source',empty:'Choose an answer before checking.',review:'Review answers',reset:'Start over',resetTitle:'Start a new attempt?',resetText:'Your score and answers for this quiz will be cleared. Crossword progress will be kept.',cancel:'Keep going',confirm:'Start over',close:'Close',resultTitle:'Significance quiz complete!',resultNote:'Your score uses the first checked answer to each question. Choose a question below to review its explanation.',shortcut:'1–4 to choose · Enter to check',saved:'Progress is kept in this browser tab when you switch modes or languages.',unanswered:'Unanswered',navigation:'Choose a question',summary:'Your results',nojs:'Enable JavaScript to take the quiz.',footer:'Know the events. Understand their significance.',resetNotice:'A new attempt has started.'}};
export function fresh(){return {version:1,active:0,selected:Array(6).fill(null),answers:Array(6).fill(null),results:false};}
export function restore(value){try{const s=JSON.parse(value);if(s.version!==1||!Number.isInteger(s.active)||s.active<0||s.active>5)throw 0;for(const key of ['selected','answers'])if(!Array.isArray(s[key])||s[key].length!==6||s[key].some(x=>x!==null&&(!Number.isInteger(x)||x<0||x>3)))throw 0;for(let i=0;i<6;i++)if(s.answers[i]!==null)s.selected[i]=s.answers[i];s.results=!!s.results&&s.answers.every(x=>x!==null);return s;}catch{return fresh();}}
export function submit(s){const i=s.active;if(s.answers[i]!==null||s.selected[i]===null)return false;s.answers[i]=s.selected[i];return true;}
export function stats(s){return {answered:s.answers.filter(x=>x!==null).length,score:s.answers.filter((x,i)=>x===correct[i]).length};}
